apiVersion: v1
kind: ServiceAccount
metadata:
  name: constellation-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "constellation.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: constellation-operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "constellation.labels" . | nindent 4 }}
